# permissions for end users to edit hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-editor-role
rules:
  - apiGroups:
      - myapp.whichxjy.com
    resources:
      - hellos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - myapp.whichxjy.com
    resources:
      - hellos/status
    verbs:
      - get
