# permissions for end users to view hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-viewer-role
rules:
  - apiGroups:
      - myapp.whichxjy.com
    resources:
      - hellos
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - myapp.whichxjy.com
    resources:
      - hellos/status
    verbs:
      - get
